Update step-3-proof-of-concept-connecting-to-sql-using-pyodbc.md
I tried to use the INSERT code in my Python script and kept running into an issue where the record DOES get inserted into my table but I keep getting this error with pyodbc:

    row = cursor.fetchone()
pyodbc.ProgrammingError: No results.  Previous SQL was not a query.

In the case of this insert, I really don't expect anything to be returned - I just want to ensure the data is inserted into my table (which I've verified and can confirm). So I used a slightly different technique where I removed the cursor.fetchone() and instead have pyodbc return something that I can handle easier with my script. Using the code above I get a "0" returned which is good enough (it's not erroring anymore).