Update all-transact-sql.md
you need to double the ' otherwise you get this error ,
Execution failed due to an unexpected error: 
Error: SQL Execution error: A fatal error occurred.
Incorrect syntax was encountered while PRINT 'At least one item for this order can't be manufactured in specified number of days.' 
ELSE 
PRINT 'All items for this order can be manufactured in the specified number of days or less.' ; was being parsed.